### ISSUE TITLE
Import script fails at writing `pflanzjahr` to database

### ISSUE THREAD

**Issue by sjockers** [technologiestiftung/giessdenkiez-de-tree-data#24]
The Import script (`main.py`) expects the `pflanzjahr` column to be of type text, but it is actually of type integer.

```
psycopg2.errors.DatatypeMismatch: column "pflanzjahr" is of type integer but expression is of type text
LINE 1: ... gattung = tree_updates_tmp.gattung, pflanzjahr = tree_updat...
                                                             ^
HINT:  You will need to rewrite or cast the expression.
```

Probably related to this change in the API: https://github.com/technologiestiftung/giessdenkiez-de-postgres-api/pull/186

**Comment by sjockers** [comment]
For reference: An easy workaround is to manually change the column type before importing data to `text`, and after the import back to `int4`.

**Comment by ff6347** [comment]
@sjockers We will pretty soon update this repo since the new Baumkataster is already live in Berlin. @julizet will take care of this. 

And yes it is related to the database migration to supabase and changing it to be a int from text

**Comment by julizet** [comment]
@sjockers : I am currently working on this and found this little line of code to fix the issue:
`updated_trees['pflanzjahr'] = updated_trees['pflanzjahr'].astype(int)`

Please see this commit: https://github.com/technologiestiftung/giessdenkiez-de-tree-data/commit/39c02569934342b1f61b4c65bc68cc55cd90665b and thank you for the hint

**Comment by sjockers** [comment]
Thanks Julia, that makes sense! Let's keep this open issue until the change makes it into the main branch.

**Comment by julizet** [comment]
short update: I ran into several problems that are due to some flaws within the dataset. In order to make the script more fail-safe I now use a more sophisticated approach that:
-  also looks for NaN and replaces them with 0
- replaces all values that have more than 4 integers

You can find the latest commit here: https://github.com/technologiestiftung/giessdenkiez-de-tree-data/commit/b60947b409f64fe7618b482cbdcd7357acde842a
